services:
  django:
    build:
      context: ./django
    ports:
      - "8000:8000"
    volumes:
      - ./django/app:/app
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - EMAIL_API_KEY = ${EMAIL_API_KEY}
    env_file:
      - .env

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi/app:/app
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - OPENAI_API_KEY = ${OPENAI_API_KEY}
      - STABLE_DIFFUSION_KEY = ${STABLE_DIFFUSION_KEY}
      - REGION_NAME = ${REGION_NAME}
      - S3_BUCKET_NAME = ${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY = ${AWS_SECRET_ACCESS_KEY}
      - S3_URL = ${S3_URL}
    env_file:
      - .env

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql  # Mount a named volume for MySQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django
      - fastapi
