version: '3'

services:
  django:
    build:
      context: ./django
    ports:
      - "8000:8000"
    volumes:
      - ./django/app:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypass

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi/app:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypass

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - ./mysql_data:/var/lib/mysql  # Mount a named volume for MySQL data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - django
      - fastapi
