# Generated by Django 5.0.6 on 2024-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(verbose_name='question')),
                ('is_active', models.BooleanField(default=True, verbose_name='activation')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice')], max_length=10)),
            ],
        ),
    ]
