# Generated by Django 5.0.6 on 2024-05-12 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 5, 35, 34, 909344, tzinfo=datetime.timezone.utc)),
        ),
    ]
