# Generated by Django 5.0.6 on 2024-05-12 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_image_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 9, 4, 54, 801599, tzinfo=datetime.timezone.utc)),
        ),
    ]
