# Generated by Django 5.0.6 on 2024-05-12 18:14

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_image_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 18, 14, 28, 351490, tzinfo=datetime.timezone.utc)),
        ),
    ]
