# Generated by Django 5.0.5 on 2024-05-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('member_email', models.EmailField(max_length=100, unique=True)),
                ('member_password', models.CharField(max_length=255)),
                ('img_uuid', models.CharField(max_length=255)),
                ('img_generate_count', models.PositiveSmallIntegerField(default=0)),
                ('auth_group', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('mem_waiting', models.BooleanField(default=False)),
                ('mem_number', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
