# Generated by Django 5.0.6 on 2024-05-09 17:39

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_email', models.EmailField(max_length=100, unique=True)),
                ('member_password', models.CharField(max_length=255, null=True)),
                ('img_uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('img_generate_count', models.PositiveSmallIntegerField(default=0)),
                ('auth_group', models.CharField(choices=[('general', '일반'), ('staff', '스태프'), ('admin', '관리자')], default='general', max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('mem_waiting', models.BooleanField(default=False)),
                ('mem_number', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=255)),
                ('keyword_input', models.TextField()),
                ('generating_count', models.SmallIntegerField(default=0)),
                ('style_code', models.CharField(max_length=20)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 5, 16, 17, 39, 52, 999447, tzinfo=datetime.timezone.utc))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
